### ISSUE TITLE
Build failure on OSX

### ISSUE THREAD

**Issue by amirmc** [dsheets/ocaml-sodium#27] opened 2015-07-26 16:40 UTC
`opam install sodium` fails with:

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of sodium failed at "make".
Processing  1/1: [sodium: ocamlfind remove]
#=== ERROR while installing sodium.0.5.0 ======================================#
# opam-version 1.2.2
# os           darwin
# command      make
# path         /Users/amir/.opam/signpost/build/sodium.0.5.0
# compiler     system (4.02.2)
# exit-code    2
# env-file     /Users/amir/.opam/signpost/build/sodium.0.5.0/sodium-10155-6d07ae.env
# stdout-file  /Users/amir/.opam/signpost/build/sodium.0.5.0/sodium-10155-6d07ae.out
# stderr-file  /Users/amir/.opam/signpost/build/sodium.0.5.0/sodium-10155-6d07ae.err
### stdout ###
# [...]
# ocamlfind ocamlc -c -bin-annot -safe-string -package ctypes.stubs -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib -o lib_gen/sodium_typegen.cmo lib_gen/sodium_typegen.ml
# ocamlfind ocamlc -linkpkg -package ctypes.stubs lib_gen/sodium_types.cmo lib_gen/sodium_typegen.cmo -o lib_gen/sodium_typegen.byte
# lib_gen/sodium_typegen.byte
# cc -I /Users/amir/.opam/signpost/lib/ctypes -I /usr/local/lib/ocaml -o lib_gen/sodium_types_detect lib_gen/sodium_types_detect.c
# + cc -I /Users/amir/.opam/signpost/lib/ctypes -I /usr/local/lib/ocaml -o lib_gen/sodium_types_detect lib_gen/sodium_types_detect.c
# lib_gen/sodium_types_detect.c:1:10: fatal error: 'sodium.h' file not found
# #include <sodium.h>
#          ^
#1 error generated.
# Command exited with code 1.
### stderr ###
# make: *** [all] Error 10
```

System details:

```
$ opam config report
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  signpost*
# last-update     2015-07-26 16:00
```

```
$ brew --version
0.9.5
```

```
$ brew info libsodium
libsodium: stable 1.0.3 (bottled), HEAD
NaCl networking and cryptography library
https://github.com/jedisct1/libsodium/
/usr/local/Cellar/libsodium/1.0.3 (62 files, 1.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libsodium.rb
==> Options
--universal
    Build a universal binary
--HEAD
    Install HEAD version
```

```
$ cc --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
```

I'm on OSX 10.10.4 (Yosemite).

**Comment by beurdouche** [comment] 2015-10-04 18:45
I have the same problem under OSX 10.11, the current version of ocaml-sodium does not build when installed from Opam =(
Is there an indication of what the problem could be ?

**Comment by beurdouche** [comment] 2015-10-04 22:02
After reinstalling the XCode Command line tools `xcode-select --instal`, the problem is solved, I don't know why though... Sorry for the noise.

**Comment by dsheets** [comment] 2016-12-04 11:29
This looks like a local configuration issue. I've seen the build complete many times on OS X and haven't received any recent reports so I'm going to close this as I can't reproduce it. Feel free to re-open if you have a lead on reproduction.

**Closed by dsheets** 2016-12-04 11:29 UTC
